# Starlify configuration
starlify:
  apiKey: ""
  systemId: ""
  baseUrl: "https://api.starlify.com/hypermedia"
  agentId: ""

# Kafka configuration
kafka:
  host: "127.0.0.1"
  port: ""
  oauth:
    token: ""